# book & aritcle basic endpoints

@hostname=localhost
@port=5544
@basePath=/api/v1
@host=http://{{hostname}}:{{port}}{{basePath}}

@basicAuth = Basic hono:acoolproject
# @route = /article
@route = /book

GET {{host}}{{route}}
Accept: application/json
authorization: {{basicAuth}}

###

@param = 1
GET {{host}}{{route}}/{{param}}
Accept: application/json
authorization: {{basicAuth}}

###

POST {{host}}{{route}}
content-type: application/json
authorization: {{basicAuth}}

{ "number": 88765, "book": "The Great Gatsby" }

###

PUT {{host}}{{route}}
Accept: application/json
content-type: application/json
authorization: {{basicAuth}}

{
    "id": 2,
    "book": "Memoirs of a Geisha"
}

###

DELETE  {{host}}{{route}}/{{param}}
Accept: application/json
content-type: application/json
authorization: {{basicAuth}}

###